"""SPK-102 forbidden-path suite across goldens."""

from __future__ import annotations

from pathlib import Path

from python_foundry.generate import generate

FORBIDDEN = ("CLAUDE.md", ".claude", ".env", ".env.example")


def _iter_project_files(dest: Path) -> list[Path]:
    """Walk project tree, skipping venv/cache (generated by uv sync)."""
    skip_dirs = {".venv", "__pycache__", ".ruff_cache", ".pytest_cache", ".git"}
    out: list[Path] = []
    for path in dest.rglob("*"):
        if any(part in skip_dirs for part in path.parts):
            continue
        if path.is_file():
            out.append(path)
    return out


def _assert_clean(dest: Path) -> None:
    files = _iter_project_files(dest)
    names = {p.name for p in files}
    for bad in FORBIDDEN:
        assert bad not in names
    text = "\n".join(
        p.read_text(encoding="utf-8", errors="ignore") for p in files
    )
    assert "load_dotenv" not in text
    assert "python-dotenv" not in text


def _cell(tmp_path: Path, name: str, archetype: str) -> Path:
    dest = tmp_path / name
    spec = tmp_path / f"{name}.toml"
    spec.write_text(
        "\n".join(
            [
                "schema = 1",
                f'name = "{name}"',
                f'archetype = "{archetype}"',
                f'destination = "{dest}"',
                "profiles = []",
                "",
            ]
        ),
        encoding="utf-8",
    )
    generate(spec_path=spec, destination=dest)
    return dest


def test_spk102_cli_clean(tmp_path: Path) -> None:
    _assert_clean(_cell(tmp_path, "c", "cli"))


def test_spk102_scripts_clean(tmp_path: Path) -> None:
    _assert_clean(_cell(tmp_path, "s", "scripts"))


def test_spk102_data_etl_clean(tmp_path: Path) -> None:
    _assert_clean(_cell(tmp_path, "d", "data-etl"))
